
variables:
  toolset: v142
  generator: 'Visual Studio 16 2019'

jobs:
- job: vcpkg
  strategy:
    matrix:
      ARM:
        platform: ARM
        cmake_platform: ARM
        configuration: Release
      x86:
        platform: x86
        cmake_platform: Win32
        configuration: Release
      x64:
        platform: x64
        cmake_platform: x64
        configuration: Release
  pool:
    vmImage: windows-2019
  steps:
    - script: |
        @ECHO ON
        echo %generator%
        echo %toolset%
        REM make sure the latest version of git is installed
        choco upgrade git ninja -y
        ninja --version
        cmake --version
        REM manually update vcpkg
        cd "C:\Tools\vcpkg"
        git pull
        .\bootstrap-vcpkg.bat
        cd $(Build.SourcesDirectory)
        vcpkg install glib:%platform%-windows || type C:\Tools\vcpkg\buildtrees\libffi\config-arm-windows-out.log
      displayName: 'Prerequisites'
    - script: |
        @ECHO ON
        mkdir build
        cd build
        cmake -Werror=dev -G "%generator%" -A %TARGET_PLATFORM% -T "%toolset%" -Denable-pkgconfig=0 -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_VERBOSE_MAKEFILE=1 -DNO_GUI=1 ..
        REM build libfluidsynth and fluidsynth exec
        cmake --build . --config Release
      displayName: 'Compile fluidsynth'
    - script: |
        @ECHO ON
        REM build and exec unittests, unless when cross-compiling
        if not "%platform%"=="ARM" ( cmake --build build --config Release --target check )
      displayName: 'Execute Unittests'
    - script: |
        @ECHO ON
        cd build
        cmake --build . --config Release --target install || exit -1
        del $(Build.ArtifactStagingDirectory)\bin\concrt*.dll
        del $(Build.ArtifactStagingDirectory)\bin\vcruntime*.dll
        del $(Build.ArtifactStagingDirectory)\bin\msvcp*.dll
        del $(Build.ArtifactStagingDirectory)\lib\instpatch*.lib
        del $(Build.ArtifactStagingDirectory)\lib\pkgconfig\libinstpatch*.pc
        rd $(Build.ArtifactStagingDirectory)\include\libinstpatch-2 /s /q
      displayName: 'Copy Artifacts'
    - task: PublishBuildArtifacts@1
      inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: fluidsynth-vcpkg-$(platform)
